name: publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set up npm auth
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm login
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Install Dependencies
        run: npm install

      - name: Build module
        run: npm run build

      - name: Publish to npm
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          if npm view three-manga@$VERSION version &> /dev/null; then
            echo "Version $VERSION already published. Skipping publish."
          else
            echo "Publishing version $VERSION"
            npm publish
          fi

      - name: Upload module
        uses: actions/upload-artifact@v3
        with:
          name: three-manga
          path: dist
